# Generated by Django 4.1 on 2022-09-09 12:19

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=200, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(upload_to=file_upload.models.upload_to, verbose_name='Image')),
            ],
        ),
    ]
